name: Events exercices

on:
  push:
    branches:
      - 'dev'
      - 'feat/**'
    branches-ignore:
      - 'staging'
    paths:
      - '**.ts'
      - 'joke-app/**'
      
  pull_request:
    types:
      - opened
      - closed
      
  schedule:
    - cron: "*/5 * * * *"
    - cron: "30 */1 * * *"
    - cron: "0 3 * * 2"
  

jobs:
  print-event:
    runs-on: ubuntu-latest

    steps:
      - name: Print the event that triggered this workflow
        run: |
          echo ${{ github.event_name }}

      - name: Print the current time
        run: |
          echo $(date)
